version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04
      - image: juampynr/circleci-db:latest
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apt-get update
            apt-get install --yes mysql-client
      - run:
          name: Enjoy database
          command: |
            mysql -uroot -proot -h127.0.0.1 wikimedia_images -e "select count(*) from image;"



