version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04
      - image: mariadb:10.4
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: world

    steps:
      - checkout

      - run:
          command: |
            apt-get update
            apt-get install wget
            wget http://downloads.mysql.com/docs/world.sql.gz



